2024-06-25 21:38:58 +0000 - dagster - DEBUG - data_ingestion_job - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - 626 - LOGS_CAPTURED - Started capturing logs in process (pid: 626).
2024-06-25 21:38:58 +0000 - dagster - DEBUG - data_ingestion_job - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - 626 - run_dbt_c7093 - STEP_START - Started execution of step "run_dbt_c7093".
2024-06-25 21:38:58 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Executing command: dbt --no-use-colors --log-format json build --project-dir /opt/dagster/app/ecommerce_dema/utils/../../dbt --profiles-dir /opt/dagster/app/ecommerce_dema/utils/../../dbt --select fqn:*
2024-06-25 21:39:00 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Running with dbt=1.8.2
2024-06-25 21:39:00 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Registered adapter: postgres=1.8.2
2024-06-25 21:39:00 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Found 1 model, 2 sources, 415 macros
2024-06-25 21:39:00 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093
2024-06-25 21:39:00 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Concurrency: 4 threads (target='prod')
2024-06-25 21:39:00 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - 1 of 1 START sql incremental model public.order_inventory ...................... [RUN]
2024-06-25 21:39:01 +0000 - dagster - ERROR - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - 1 of 1 ERROR creating sql incremental model public.order_inventory ............. [ERROR in 0.16s]
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Finished running 1 incremental model in 0 hours 0 minutes and 0.28 seconds (0.28s).
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Completed with 1 error and 0 warnings:
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093
2024-06-25 21:39:01 +0000 - dagster - ERROR - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 -   Runtime Error in model order_inventory (models/order_inventory.sql)
  The incremental strategy 'insert_overwrite' is not valid for this adapter
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093
2024-06-25 21:39:01 +0000 - dagster - INFO - resource:dbt - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - run_dbt_c7093 - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2024-06-25 21:39:01 +0000 - dagster - ERROR - data_ingestion_job - 0501dccd-9608-4e76-b58d-e1176a2bdc86 - 626 - run_dbt_c7093 - STEP_FAILURE - Execution of step "run_dbt_c7093" failed.

dagster_dbt.errors.DagsterDbtCliHandledRuntimeError: Handled error in the dbt CLI (return code 1)

Stack Trace:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 501, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 186, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 91, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 195, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 164, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/asset_defs.py", line 344, in _dbt_op
    yield from _stream_event_iterator(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/asset_defs.py", line 246, in _stream_event_iterator
    for parsed_json_line in dbt_resource.cli_stream_json(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/core/resources.py", line 227, in cli_stream_json
    for event in execute_cli_stream(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/core/utils.py", line 190, in execute_cli_stream
    for event in _core_execute_cli(
  File "/usr/local/lib/python3.9/site-packages/dagster_dbt/core/utils.py", line 163, in _core_execute_cli
    raise DagsterDbtCliHandledRuntimeError(messages=messages)

